---
title: Our Vegan Thanksgiving for 2
author: Alexis Meskowski
date: '2020-11-20'
slug: our-vegan-thanksgiving-for-2
categories:
  - Eat
tags:
  - Thanksgiving
lastmod: '2020-11-20T13:15:08-06:00'
description: 'What we ate for Thanksgiving this year!'
show_in_homepage: yes
show_description: yes
resources:
- name: featured-image
  src: TGiving Blog Preview.png
- name: featured-image-preview
  src: TGiving Blog Preview.png
math:
  enable: false
share:
  enable: true
comment:
  enable: true
draft: true
---
## Hello friends, this is what we ate for Thanksgiving this year!

<!-- featured_image_preview is 780x234 -->


```{r, echo=FALSE}
blogdown::shortcode("youtube", "")
```

Kyle and I decided we were going to challenge ourselves to stay safe at home and make our own vegan thanksgiving meal. We did not come up with any of the recipes that we used, but we did modify them, so I will link the recipes below, and also list exactly what we used and did to make all 3 recipes very easily. 

### Recipes:

[Field Roast Celebration Roast](http://fieldroast.com/recipe/celebration-roast-with-gravy-and-cumin-roasted-carrots/){target="_blank"}

[Vegan Gravy](https://www.noracooks.com/easy-vegan-gravy/){target="_blank"}

[Mashed Potatoes](https://www.budgetbytes.com/fluffy-garlic-herb-mashed-potatoes/){target="_blank"}

- this recipe is not vegan, but it easily made vegan by replacing the milk and butter with vegan milk and butter

Amount of servings: 4

:::: {style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;"}

::: {}

### <u>Ingredients</u>

- Field Roast Celebration Roast
- 1.5 lbs of russet potatoes
- 1 can of green beans
- 2.5 cups vegetable broth
- 

::: 

::: {}

### <u>Preparation</u> 

1. Preheat the oven to 350° F
1. Start the pot for the gravy on medium heat and stir in all the ingredients to begin boiling
1. Wash and cube the potatoes, setting aside in a small bowl
1. Stir the gravy pot again and start another pot with enough water to cover the potatoes on medium heat
1. Take your thawed Celebration Roast out of the fridge, remove the packaging, and place it in a baking dish. Brush the roast with olive oil and pour some vegetable broth in the bottom of the dish. Cover with foil and place in the oven for 45 minutes.
1. Finish gravy, set aside on trivet, and hang out for a few minutes while you wait to start the potatoes. We waited until we had 10 minutes left on the roast so everything would be ready together.
1. Start potatoes in the boiling water for 10 minutes
1. Start a smaller pan with vegan butter on medium-low heat and toss in some onions and garlic, Once these are translucent, a can of drained green beans can be added and sauteed. 
1. Drain the potatoes and set aside in the same bowl used to store them in step 3. Bring the rest of the mashed potato ingredients to a boil together in the pot used to boil the potatoes. 
1. Finish green beans and set aside on the stove top.
1. Remove foil from roast and cook until browned on the outside, about 15 more minutes.
1. Once mashed potato pot is boiling, add potatoes and mash using a potato masher or big fork.
1. Remove roast from the oven, carve, and serve with all sides and plenty of gravy.
1. Enjoy! :)

:::

::::

<br>

---

### Notes:

- 




