project:
  type: website

website:
  title: "Eat Game Love"
  site-url: https://eatgamelove.net
  favicon: "images/favicon/apple-touch-icon.png"
  search: false
  google-analytics:
    tracking-id: "G-HTJZRVJYRW"
    anonymize-ip: true
  open-graph: true
  twitter-card: true
  navbar:
    logo: "images/egl_hc_logo_smol.png"  
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: FAQ.qmd
        text: FAQ
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: [minty, custom.scss]
    css: styles.css
    toc: false
    link-external-icon: false
    link-external-newwindow: true

editor: visual
execute: 
  freeze: auto
  
resources:
  - CNAME