project:
  type: website

website:
  title: "Eat Game Love"
  navbar:
    logo:  "EGL_HC_Logo_Smol.png"  
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: FAQ.qmd
        text: FAQ
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: [minty, custom.scss]
    css: styles.css
    toc: false
    link-external-icon: false
    link-external-newwindow: true

editor: visual
execute: 
  freeze: auto