---
title: Sweet Potato Medallions
author: Alexis Meskowski
date: '2020-11-02'
slug: sweet-potato-medallions
categories:
  - Eat
tags:
  - Sweet Potato
lastmod: '2020-11-02T12:20:35-06:00'
description: 'The best and easiest way to have spicy and savory sweet potatoes!'
show_in_homepage: yes
show_description: yes
resources:
- name: featured-image
  src: Sweet Potato Medallions.png
- name: featured-image-preview
  src: Sweet Potato Medallions.png
math:
  enable: false
share:
  enable: true
comment:
  enable: true
---
## Hello friends, this is our favorite way to eat sweet potatoes!

<!-- featured_image_preview is 780x234 -->




Amount of servings: 2

:::: {style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;"}

::: {}

### <u>Ingredients</u>

- 2 medium sweet potatoes
- 2 tbsp [Nutzo](https://www.nuttzo.com/product/26oz-organic-paleo-power-fuel-crunchy/){target="_blank"} (or another nut butter)
- 2 tbsp Sriracha 
- .5 tsp garlic powder
- .5 tsp cayenne
- Pinch of salt 
- Pinch of pepper
- .5 tsp olive oil

::: 

::: {}

### <u>Preparation</u> 

1. Wash, scrub, and dry sweet potatoes 
2. Cut into slices about 1/4 inch thick
3. Pre-heat air fryer or oven to 350°
4. Toss sweet potato slices in a bowl with olive oil and spices until coated
5. Place slices either in the frying basket or on a non-stick baking sheet, evenly spread
6. Cook sweet potato slices for 14 minutes, tossing in the basket or turning on the baking sheet halfway through.
7. Plate and add a smear of Nutzo and a drizzle of sriracha to each slice
8. Enjoy!

:::

::::

<br>

---

### Notes:

- We prefer to make this in the air fryer so that the sweet potatoes get a little more crispy, but the oven works perfectly fine if you don't have an air fryer or you don't feel like pulling yours out!
- Kyle and I buy Nutzo at Costco in bulk and use it for a lot of things in the place of other nut butters such as putting it on toast, in porridge, or on the side with an apple. If you don't have it on hand or can't find it easily (I know I have seen it at Wal-Mart), any nut butter will work fine. 
- Play around with the spices you use, if cayenne is too hot, use paprika. Or maybe you have a favorite spice blend on hand that you would like to try. We're always changing it up to make things interesting, but this is the most basic way we make this recipe. 




