---
title: Easy Vegan Breakfast Burrito
author: Alexis Meskowski
date: '2020-11-28'
slug: [easy-vegan-breakfast-burrito]
categories:
  - Eat
tags:
  - Breakfast
  - Tofu
lastmod: '2020-11-28T00:41:16-06:00'
description: 'Lexi fill this in plz <3'
show_in_homepage: yes
show_description: yes
resources:
- name: featured-image
  src: tofu_burrito_blog_preview.png
- name: featured-image-preview
  src: tofu_burrito_blog_preview.png
math:
  enable: false
share:
  enable: true
comment:
  enable: true
draft: false
---

<br>

## Hello friends, here is one of our favorite vegan breakfast burrito recipes!

We had a request to show how to cook with tofu, so we chose one of the easiest ways to use tofu, without even having to press it! 

**We use mainly two types of tofu when we cook, the firmest (extra firm) and the softest (soft) kinds.**

**The firmer kind is good for:** 

- air frying to make it super crispy

- baking in the oven with a marinade to make it super juicy

**The softer kind is good for:**

- blending up in soups or smoothies

- mashing up in a pan to make a scramble
 
*For our breakfast burrito we chose the softest and decided to make a scramble with it.*

Because of this, there was no tofu press involved, however it is extremely simple to press tofu. Kyle and I bought [this tofu press](https://www.amazon.com/EZ-Tofu-Press-Removes-Texture/dp/B007LLGMG2/ref=sr_1_6?dchild=1&keywords=tofu+press&qid=1606687990&sr=8-6){target="_blank"} off of Amazon and it works amazing. We simply put the block in between the two boards and twist the screws tighter, allowing it to drain over a bowl or container for about 20 minutes. It can help to twist the screws tighter every few minutes to get all the extra water out.

If you'd like to make your tofu really tasty you can marinade it very easily like in our [fried rice recipe](https://www.eatgamelove.com/2020-11-01-tofu-fried-rice/){target="_blank"} or this [BBQ tofu recipe](https://www.whereyougetyourprotein.com/bbq-tofu-with-caramelized-onions/#mv-creation-124-jtr){target="_blank"} that we love.

<br>

```{r, echo=FALSE, eval=TRUE}
blogdown::shortcode("youtube", "NoSs3fusvi8")
```

<br>

Amount of servings: 2

:::: {style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;"}

::: {}

### <u>Ingredients</u>

- 2.0 tortillas
- Beans or some meat replacement like Beefless Crumbles
- 1.0 block of soft tofu
- 1.5 ounces of plant-based milk (plain)
- 1.0 onion
- 1.0 bell pepper
- 2.0 cloves of garlic
- 1.0 tbsp taco seasoning
- 1.0 pinch of salt
- 1.0 pinch of pepper

#### <u>Optional</u>

- Crispy potatoes
- Vegan shredded cheddar cheese
- Vegan sour craem
- Hot sauce

::: 

::: {}

### <u>Preparation</u> 

1. Start a pan on medium heat and toss in a little olive oil
1. Chop garlic and veggies, then add to the pan and cook until slightly translucent
1. We made some crispy potatoes in our air fryer so if you are doing that scrub and wash then chop and toss in some oil with your favorite spices. We let them go for 15 minutes at 400°F.
1. Then ,add beans to the pan and saute that as well until cooked through
1. Add in a block of soft tofu and mash with a potato masher, crumble with your hands, or chop up with your cooking utensil.
1. Add taco seasoning, spices, and a splash of plant based milk and continue to stir a few more minutes until everything is incorporated into the “scramble”
1. Place “scramble” contents in the tortilla and top with your favorite toppings including the crispy potatoes if you so choose
1. Roll and enjoy :)


:::

::::

<br>

---

### Notes:
- We bought some black bean patties from Costco that we don't love, but this recipe helps us to get rid of them so we used that instead of some black beans
- We would have added vegan cheddar but we didn't have any on hand
- Add any of your favorite veggies, toppings, or spices to this, the combinations are truly endless
